name: DisplayEntityUtils
version: '${project.version}'
main: net.donnypz.displayentityutils.DisplayEntityPlugin
api-version: '1.21'
author: DonnyPZ
load: POSTWORLD
softdepend:
  - MythicMobs
  - Skript
commands:
  managedisplays:
    aliases: [mdis]
    description:
    usage:
